server:
  port: 81
  servlet:
    context-path: /cj

country:
  hello: 1


user1: dog

customer:
  - washing car
  - proxy delivery
  - cleaning house


Win:
  dir: C:/program/data
  element:
    - a
    - b
    - c

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db0?serverTimezone
    username: root
    password: 123456


tmp:
  dir: ${Win.dir}/tmpdir