# development
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/coh2?serverTimezone=GMT
      username: root
      password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true


server:
  port: 81


logging:
  level:
    root: error