# development
spring:
  config:
    activate:
      on-profile:
        - pro
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db0?serverTimezone=GMT
      username: root
      password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true


server:
  port: 81


logging:
  group:
    dao: "com.coh.ssm.dao"
    service: "com.coh.ssm.service"

  level:
    root: "info"
    service: "warn"

  pattern:
    console: "%d %clr(%5p) --- [%clr(%16t){blue}] %clr(%-40.40c){cyan} : %m %n"


  file:
    name: "server.log"
    path: /

  logback:
    rollingpolicy:
      file-name-pattern: "server.%d{yyyy--mm--dd}.%i.log"
      max-file-size: "4KB"




